# Generated by Django 5.0.6 on 2024-06-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Sports', 'Sports'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Footwear', 'Footwear'), ('Hardware', 'Hardware')], max_length=20, null=True),
        ),
    ]
