# Generated by Django 5.0.6 on 2024-06-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_model_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='model_no',
        ),
    ]
