# Generated by Django 5.0.6 on 2024-06-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='model_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
