# Generated by Django 5.0.6 on 2024-07-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Issued', 'Not Issued'), ('Issued', 'Issued')], default='Not Issued', max_length=10),
        ),
    ]
