# Generated by Django 5.0.6 on 2024-06-11 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(default='https://imgs.search.brave.com/I80kyHeaeBLEYN60dAmrDkSEg5nLVhvdnqbJXpcomk4/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJzLmNvbS9p/bWFnZXMvaGQvYWxi/ZXJ0LWVpbnN0ZWlu/LXBpY3R1cmVzLTMx/ODUteC0zMTIwLW0x/eHRvN3gwaTlweTM0/YjIuanBn', upload_to='Profile_Image')),
                ('staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
